openapi: 3.0.0
info:
  title: Folksoul API
  description: Documentation for folksoul API
  version: 1.0.0

servers:
  - url: https://folksoul-api.otar.redberryinternship.ge
    description: production server
  - url: http://localhost:8000/
    description: local server
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /login:
    post:
      summary: Login with admin credentials
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nickname:
                  type: string
                password:
                  type: string
              example:
                nickname: user
                password: folksoul
              required:
                - nickname
                - password
      responses:
        '200':
          description: Successfully logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: object
                    properties:
                      nickname:
                        type: string
                      JWTToken:
                        type: string
                    example:
                      nickname: admin
                      JWTToken: 123
        '400':
          description: Wrong nickname or password
        '422':
          description: Invalid request body formation

  /band-members:
    get:
      summary: Get band members list
      tags:
        - Band Members
      responses:
        '200':
          description: Band members received successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: object
                    properties:
                      bandMembers:
                        type: array
                        items:
                          type: object
                          properties:
                            _id:
                              type: string
                            instrument:
                              type: string
                            orbitWidth:
                              type: number
                            color:
                              type: string
                            bio:
                              type: string
                        example:
                          _id: 123
                          name: ხვიჩა
                          instrument: გიტარა
                          orbitWidth: 10
                          color: '#ffffff'
                          bio: ბიოგრაფია

  /band-member:
    post:
      summary: Add band member
      tags:
        - Band Members
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                instrument:
                  type: string
                orbitWidth:
                  type: number
                color:
                  type: string
                bio:
                  type: string
              example:
                name: ხვიჩა
                instrument: გიტარა
                orbitWidth: 10
                color: '#FFFFFF'
                bio: ბიოგრაფია
              required:
                - name
                - instrument
                - orbitWidth
                - color
                - bio
      responses:
        '200':
          description: Band member added successfully
        '401':
          description: Not authorized
        '422':
          description: Invalid request body formation
  /band-member/avatar/{id}:
    put:
      summary: Add avatar to band member
      tags:
        - Band Members
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Band member id
      requestBody:
        description: Only png, jpg, jpeg and svg photo formats are allowed
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      responses:
        '200':
          description: Avatar added successfully
        '400':
          description: Wrong band member id
        '401':
          description: Not authorized
        '422':
          description: No image or invalid id provided
  /band-member/{id}:
    get:
      summary: Get single band member
      tags:
        - 'Band Members'
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Band member id
      responses:
        '200':
          description: Band member received successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: object
                    properties:
                      bandMember:
                        type: object
                        properties:
                          _id:
                            type: string
                          instrument:
                            type: string
                          orbitWidth:
                            type: number
                          color:
                            type: string
                          bio:
                            type: string
                        example:
                          _id: 123
                          name: ხვიჩა
                          instrument: გიტარა
                          orbitWidth: 10
                          color: '#ffffff'
                          bio: ბიოგრაფია
        '400':
          description: Wrong band member id
        '422':
          description: Invalid id param formation
    put:
      summary: Update band member
      tags:
        - 'Band Members'
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Band member id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                instrument:
                  type: string
                orbitWidth:
                  type: number
                color:
                  type: string
                bio:
                  type: string
              example:
                name: ხვიჩა
                instrument: პიანინო
                orbitWidth: 12
                color: '#000000'
                bio: გასაოცარი ბიოგრაფია
              required:
                - name
                - instrument
                - orbitWidth
                - color
                - bio
      responses:
        '200':
          description: Band member updated successfully
        '400':
          description: Wrong band member id
        '401':
          description: Not authorized
        '422':
          description: Invalid request body or id param formation
    delete:
      summary: Delete band member
      tags:
        - 'Band Members'
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Band member id
      responses:
        '200':
          description: Band member deleted successfully
        '400':
          description: Wrong band member id
        '401':
          description: Not authorized
        '422':
          description: Band member id provided in invalid format

  /social-links:
    get:
      summary: Get social links list
      tags:
        - Social Links
      responses:
        '200':
          description: Social links received successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: object
                    properties:
                      socialLinks:
                        type: array
                        items:
                          type: object
                          properties:
                            _id:
                              type: string
                            name:
                              type: string
                            link:
                              type: string
                        example:
                          _id: 123
                          name: facebook
                          link: https://facebook.com/folksoul
  /social-link:
    post:
      summary: Add social link
      tags:
        - Social Links
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                link:
                  type: string
              example:
                name: facebook
                link: https://facebook.com/folksoul
              required:
                - name
                - link
      responses:
        '200':
          description: Social link added successfully
        '401':
          description: Not authorized
        '422':
          description: Invalid request body formation

  /social-link/icon/{id}:
    put:
      summary: Add icon to social link
      tags:
        - Social Links
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Social link id
      requestBody:
        description: Only png, jpg, jpeg and svg photo formats are allowed
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      responses:
        '200':
          description: Icon added successfully
        '400':
          description: Wrong social link id
        '401':
          description: Not authorized
        '422':
          description: No image or invalid id provided
  /social-link/{id}:
    get:
      summary: Get single social link
      tags:
        - 'Social Links'
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Social link id
      responses:
        '200':
          description: Social link received successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  data:
                    type: object
                    properties:
                      socialLink:
                        type: object
                        properties:
                          _id:
                            type: string
                          name:
                            type: string
                          link:
                            type: string
                        example:
                          _id: 123
                          name: facebook
                          link: https://facebook.com/folksoul
        '400':
          description: Wrong social link id
        '422':
          description: Invalid id param formation
    put:
      summary: Update social link
      tags:
        - 'Social Links'
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Social link id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                link:
                  type: string
              example:
                name: instagram
                link: https://instagram.com/folksoul
              required:
                - name
                - link
      responses:
        '200':
          description: Social link updated successfully
        '400':
          description: Wrong social link id
        '401':
          description: Not authorized
        '422':
          description: Invalid request body or id param formation
    delete:
      summary: Delete social link
      tags:
        - 'Social Links'
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Social link id
      responses:
        '200':
          description: Social link deleted successfully
        '400':
          description: Social link id
        '401':
          description: Not authorized
        '422':
          description: Social link id provided in invalid format
